using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace FAQs.Models
{
    public class FAQ
    {
        //needs to be generated by database
        [Key]
        public int QuestionId { get; set; }
        public string QuestionName { get; set; }
        public string Answer { get; set; }


        // need foreign key fields to relate it to topic and category classes
        [Required(ErrorMessage = "Please enter a Category.")]
        public string CategoryId { get; set; }
        public Category Category { get; set; }

        [Required(ErrorMessage = "Please enter a Topic.")]
        public string TopicId { get; set; }
        public Topic Topic { get; set; }

    }
}
