// <auto-generated />
using FAQs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAQs.Migrations
{
    [DbContext(typeof(FAQContext))]
    [Migration("20220429215715_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FAQs.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "gen",
                            CName = "General"
                        },
                        new
                        {
                            CategoryId = "hist",
                            CName = "History"
                        });
                });

            modelBuilder.Entity("FAQs.Models.FAQ", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"), 1L, 1);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QuestionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("QuestionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer = "In 2011.",
                            CategoryId = "hist",
                            QuestionName = "When was Bootstrap first released?",
                            TopicId = "boot"
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer = "In 2002.",
                            CategoryId = "hist",
                            QuestionName = "When was C# first released?",
                            TopicId = "csharp"
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer = "In 1995.",
                            CategoryId = "hist",
                            QuestionName = "When was JavaScript first released?",
                            TopicId = "js"
                        },
                        new
                        {
                            QuestionId = 4,
                            Answer = "A general purpose scripting language that executes in a web browser.",
                            CategoryId = "gen",
                            QuestionName = "What is JavaScript?",
                            TopicId = "js"
                        });
                });

            modelBuilder.Entity("FAQs.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = "all",
                            TName = "All FAQs"
                        },
                        new
                        {
                            TopicId = "boot",
                            TName = "Bootstrap"
                        },
                        new
                        {
                            TopicId = "csharp",
                            TName = "C#"
                        },
                        new
                        {
                            TopicId = "js",
                            TName = "JavaScript"
                        });
                });

            modelBuilder.Entity("FAQs.Models.FAQ", b =>
                {
                    b.HasOne("FAQs.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAQs.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
